// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

// Init provides a mock function with given fields: username, password
func (_m *EmailSender) Init(username string, password string) {
	_m.Called(username, password)
}

// SendEmailSimple provides a mock function with given fields: sbjt, to, msg
func (_m *EmailSender) SendEmailSimple(sbjt string, to string, msg string) error {
	ret := _m.Called(sbjt, to, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailSimple")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(sbjt, to, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailSender creates a new instance of EmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSender {
	mock := &EmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
